name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./terraform
      TERRAFORM_VERSION: 1.1.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/terraform
            /usr/local/bin/tfsec
            /usr/local/bin/tflint
            ~/.terraform.d/plugin-cache
            ~/.tflint.d/plugin-cache
          key: ${{ runner.os }}-terraform-tfsec-tflint-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-terraform-tfsec-tflint-

      - name: Install prerequisities
        run: |
          sudo apt-get update
          sudo apt-get install -y bash curl wget unzip

          # Terraform, if checks if binary in cache
          if [ ! -f "/usr/local/bin/terraform" ]; then
              curl -LO https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip && \
              unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip && \
              mv terraform /usr/local/bin && \
              rm terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          fi

          # TFsec
          if [ ! -f "/usr/local/bin/tfsec" ]; then
            wget -q https://github.com/liamg/tfsec/releases/latest/download/tfsec-linux-amd64 \
              && install -m 0755 tfsec-linux-amd64 /usr/local/bin/tfsec \
              && rm tfsec-linux-amd64
          fi

          # TFlint
          if [ ! -f "/usr/local/bin/tflint" ]; then
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          fi

          # Check
          terraform --version
          tfsec --version
          tflint --version

      - name: "Auth to GCP"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform validate
        id: validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      - name: TFlint
        id: tflint
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          tflint --recursive --config "$(pwd)/.tflint.hcl"

      - name: TFsec
        id: tfsec
        working-directory: ${{ env.WORKING_DIR }}
        run: tfsec . --force-all-dirs --include-passed

      - name: checkov
        id: checkov
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          docker run -t -v ${{ github.workspace }}/terraform:/tf --workdir /tf bridgecrew/checkov --directory /tf --soft-fail

      - name: Terraform plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform plan -no-color -input=false
